### ISSUE TITLE
build_deps.sh build failures (multiple listed)

### ISSUE THREAD

**Issue by whisperity** [Ericsson/CodeCompass#107]
There are some error or unhandled cases in `build_deps.sh` which make the unattended build of the CodeCompass environment impossible:

- [x] Some parts of Boost `#include "bzlib2.h"`, but the `build_deps.sh` script does not mark `bzip2` a dependency for `boost` and the file thus does not exist. Fixed by installing `libbz2-dev` on the system, but the build script already install some bzip2, so a dependency should be added.

- [x] `makeinfo` is a tool requirement by the configure/build of `gdb`, but this tool is not automatically present on the system. Fixed by `apt-get install texinfo`.

- [x] When compiling Thrift, an error is given, which is [mentioned in the user guide](https://github.com/Ericsson/CodeCompass/blob/master/docs/deps.md#thrift-compilation-error). This step should be done automatically by `build-deps.sh`
   - Note: Instead of copying the library file, we should symlink it instead with a **relative link**: `cd CodeCompass-deps/lib64` and then `ln -s ../lib/libboost_unit_test_framework.a ./libboost_unit_test_framework.a`

- [x] The script puts `env.sh` under `CodeCompass-deps` but the prompt says `CodeCompass-install/env.sh`.

**Comment by balintkiss501** [comment]
I can confirm the wrong dependency order bug with bzip2 and boost. There's a way to install packages individually with the -p switch, so I used that workaround instead relying on system dependencies.

CodeCompass/scripts/build_deps.sh -p bzip2 && CodeCompass/scripts/build_deps.sh
