### ISSUE TITLE
Installing npm packages fail in environment -- webserver empty page

### ISSUE THREAD

**Issue by whisperity** [Ericsson/CodeCompass#112]
If the `build_deps.sh` is executed and the environment is sourced, the npm installer will fail with the message below: (`nodejs` came from the `npm` package of the package manager)

    Install npm packages...
    /usr/bin/nodejs: /home/[username]/CodeCompass/CodeCompass-deps/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/bin/nodejs)
    Installation of npm packages are finished.

The installation can continue if the user calls `make install` in the build folder **without** the environment being sourced in, and if the `install` folder is not removed, subsequent `make install`s will keep the Node modules there.)

**Comment by bruntib** [comment]
The `build_deps.sh` has been removed from the repository as it is no longer the recommended way of handling 3rd party dependencies. We have provided a documentation instead: https://github.com/Ericsson/CodeCompass/blob/master/doc/deps.md. Does this issue exist with this way of installation?

**Comment by bruntib** [comment]
Issues with build_deps.sh are not relevant any more.
