### ISSUE TITLE
"Graph generation seems to be too long."

### ISSUE THREAD

**Issue by codeorcode** [Ericsson/CodeCompass#12]
If I use "Non Reduced View" to see "Component Users" of a main.cpp file for a big project I get the following error right away: 

"Graph generation seems to be too long."

Still I can see a loading animation but I wander maybe I should get this error after a while not right away.

Also I wonder if I should wait more for the drawing to appear (in this case) or it will never appear? (I've waited like 10 minutes)

**update**: I will try "Non Reduced View" option with a simpler project, I was just curios what is displayed for a bigger project.

**Comment by bruntib** [comment]
Hello,

This "Non Reduced View" belongs to a diagram which is not added to this CodeCompass release. We will remove this button from the GUI.
