### ISSUE TITLE
Web application fails to load if Git parser was skipped

### ISSUE THREAD

**Issue by whisperity** [Ericsson/CodeCompass#122]
There is no way to skip plugins on the webserver invocation. If the parsed project has its Git plugin skipped, the webserver will throw an

> TApplicationException: boost::filesystem::directory_iterator::construct: No such file or directory: "/home/me/CodeCompass/data-dir/project/version"

which will ultimately prevent the page from loading.

**Comment by bruntib** [comment]
Search service should also be checked. If that works with skipped parser then this issue can be closed.

**Comment by bruntib** [comment]
I can't reproduce the problem, so I close the ticket. If this issue is not solved yet then please reopen it.
