### ISSUE TITLE
Set CODECHECKER_HOME environment variable!

### ISSUE THREAD

**Issue by codeorcode** [Ericsson/CodeCompass#13]
Hi.
When I try to use the following line:

CodeCompass codechecker -w /home/john/cc/workdir/ -n src_test_project  --dbport 6250 --dbuser john

 I am getting this error:

Set CODECHECKER_HOME environment variable!

even if that variable is set:

$ env | grep -i codechecker
CODECHECKER_HOME=/home/john/cc/CodeCompass/service/codechecker

I've also tried:

python /home/john/cc/CodeCompass-install/share/codecompass/cli/CodeCompass.py codechecker -w /home/john/cc/workdir/ -n src_test_project  --dbport 6250 --dbuser john

Any idea what to do?

**Comment by bruntib** [comment]
Hello,

[CodeChecker](https://github.com/Ericsson/codechecker) is another tool for static analysis. First you have to set it up and check a project with it. This tool creates an own database to which CodeCompass can connect and can read the results. In `CODECHECKER_HOME` you have to set the directory where this CodeChecker tool is located (see [this](https://github.com/Ericsson/CodeCompass/wiki/How-To-Add-CodeChecker-To-A-Project) documentation).
However CodeChecker is not necessary to run CodeCompass itself. This message is just a tip for the user why CodeChecker results can't be seen.

**Comment by bruntib** [comment]
In the new CodeCompass we don't plan to create a sub command for handling CodeChecker. When adding CodeChecker plugin it should work in a way that the connection is given during the parse session to an existing CodeChecker database. This method will not require CODECHECKER_HOME environment variable.
