### ISSUE TITLE
build_deps.sh has more dependencies than described on the documentation

### ISSUE THREAD

**Issue by TheFakeMontyOnTheRun** [Ericsson/CodeCompass#144]
So far, I needed to install _make_ and _unzip_ for a fresh Ubuntu install.

(sorry, it's a minor issue, but I believe it's worth reporting).

**Comment by whisperity** [comment]
A fresh Ubuntu install does not supply `make` (and `unzip`, for that matter) by default? :open_mouth:

**Comment by TheFakeMontyOnTheRun** [comment]
Shocking, I know ;-P
But it really doesn't. At least not the versions I tried so far (16.10 and 16.04).
