### ISSUE TITLE
build_deps.sh will fail to proceed if a dependency package install downloaded but not extracted

### ISSUE THREAD

**Issue by TheFakeMontyOnTheRun** [Ericsson/CodeCompass#145]
If a failure happens while running the script and a dependency is downloaded but not extracted, the script will not recognize the already downloaded package, but will not try to download it again either, hanging in the process.

Removing the already downloaded package will fix the issue.

**Comment by bruntib** [comment]
We have removed `build_deps.sh` from the repository as it is no longer the recommended way of installing 3rd party dependencies. We have provided a documentation instead which describes which dependencies should be installed manually and how to fix known issues of some 3rd parties: https://github.com/Ericsson/CodeCompass/blob/master/doc/deps.md. We are also planning to provide a Docker image which already contains the installed dependencies.

**Comment by TheFakeMontyOnTheRun** [comment]
Thanks! Gonna try it soon!
