### ISSUE TITLE
Refactoring 3rd parties in cmake files

### ISSUE THREAD

**Issue by bruntib** [Ericsson/CodeCompass#147]
The CMakeLists.txt files of plugins contain include and library paths of 3rd party libraries. These are needed because sometimes these are not at the common place on the hard drive (/usr/...) but on a custom place if the user installs it manually. This is not a rare usecase because for some 3rd parties some workaround is needed. However the plugin creator shouldn't know which 3rd parties are installed manually, so all these should be listed in a higher level CMakeLists.txt (e.g. in plugins/CMakeLists.txt).

**Comment by whisperity** [comment]
Can you clarify on this issue? Current `CMakeLists.txt`s only use CMake's generated variables, such as `THRIFT_LIBTHRIFT_INCLUDE_DIRS`. Do you mean these? I don't quite get the issue here.

**Comment by bruntib** [comment]
This ticket may come from the old times when these variables didn't exist. So we can close this issue.
