### ISSUE TITLE
Compile-only calls without explicit output specified will mark resulting object file as "Unknown" instead of "Binary"

### ISSUE THREAD

**Issue by whisperity** [Ericsson/CodeCompass#149]
Both `g++` and `clang` define the `-c` flag which **only** invokes compilation and not linking. This command can get arbitrary number of translation unit files as argument, for which it will create objects of the same name in the same folder (so `g++ -c a.cpp b.cpp` will result in `a.o` and `b.o`, compiled respectively).

Passing a `build.json` containing such commands will make CodeCompass:
 * Mark the files as `Unknown` instead of `Binary` in the `File` table. This currently does not cause any problems, but is a real gimmick when someone tries to look at the database on what has happened in the analysis.
 * Due to the build command itself having no _target_ specified, the file record (having kind as `Unknown`) is never added to **any** `BuildTarget` record, thus breaking the build chain stored in the database. This pulls the carpet away from under my thesis work feature to CodeCompass.

These commands work:

```
g++ -c main.cpp -o main.o
g++ -c impl.cpp -o impl.o
g++ impl.o main.o -o main.out
```

But this does not

```
g++ -c main.cpp impl.cpp
g++ main.o impl.o -o main.out
```

or equivavelently in a small test project, `g++ -c *.cpp && g++ *.o`.

**Comment by mcserep** [comment]
Is this issue related to *Earhart* or *Flash*? Has it been fixed as part of a PR without referencing this issue?

**Comment by bruntib** [comment]
In case of `g++ a.cpp b.cpp` the logger produces two JSON objects for the two translation units in the compilation database. I tried it and the binary file's type is `Binary` in the database, so it is working for me. So I close this ticket, but feel free to reopen it if there still are issues.
