### ISSUE TITLE
build system invocation during parse command

### ISSUE THREAD

**Issue by celavek** [Ericsson/CodeCompass#19]
Hi,

How would one make this work with a build system that does not invoke directly gcc or make?

I have a build system driver written in python which in turn calls CMake to generate the makefiles and after it calls make. All of that is done from within python scripts. I have built and installed Code Compass 
and I try to parse my project by passing to `-b` a shell script which calls my python script. My project builds OK, which means the script invocation works but the parser does not parse anything! I instructed it to look for CMake, my python script invocation, gcc and make using `export CC_LOGGER_GCC_LIKE="python_script:cmake:make:gcc"`, but still it does not parse anything.

Do you have any pointers on how I could overcome that?

**Comment by bruntib** [comment]
Hello,

Any build system you use, at the lowest level there should be a C/C++ compiler invocation which compiles the `.c`/`.cpp` files to executables or object files. The logger in CodeCompass catches all `exec` system calls during the compilation phase, and checks if the called command contains one of the `CC_LOGGER_GCC_LIKE` items. If so, then that command is logged into a JSON file in the `<workdir>/<projectdir>` directory. So `CC_LOGGER_GCC_LIKE` should contain the name of the C++ compiler (or at least a substring of it) which is used by your build system. CMake by default uses the `cpp` command for C++ compilation, if `CMAKE_CXX_COMPILER` is not provided, and there is a default value for `CMAKE_C_COMPILER` too. So you should use something like this: `CC_LOGGER_GCC_LIKE=g++:gcc:cpp:clang:clang++`.

**Comment by celavek** [comment]
Hi,

I was thinking that should work as you described it, but unfortunately there is something that escapes me. I tried your suggestions but it still does not work. My project gets build successfully, and I do a clean build every time, but I do not get anything out of the parser. The only files it parses are the files used to check for some compiler features at the beginning of the build process. Attached is my parse log.
[parselog.txt](https://github.com/Ericsson/CodeCompass/files/641661/parselog.txt)

I would be more than willing to try any other suggestions.

Thanks

**Comment by bruntib** [comment]
Hi,

Doesn't your build system have some kind of verbose flag? Currently I can't see another way to find the problem than determining which compiler is being used exactly. For example CMake can be given VERBOSE=1 variable which forces the build system to print the build command that contains the compiler name at the beginning.

**Comment by bruntib** [comment]
Hi,

Have you managed to create a compilation database? Since then CodeCompass has been rewritten, so logging and parsing process has slightly changed. For logging you should follow this documentation: https://github.com/Ericsson/CodeCompass/blob/master/doc/usage.md#1-generate-compilation-databse. Parsing the project is also described in this documentation.

**Comment by bruntib** [comment]
I close the ticket for now. If there are still problems with logging, then please reopen it.
