### ISSUE TITLE
CodeCompass is incompatible with thrift 0.9.3

### ISSUE THREAD

**Issue by APTX** [Ericsson/CodeCompass#20]
Thrift 0.9.3 introduced a change:
> [THRIFT-727] - support native C++ language specific exception message

This change generates a what() method for all generated exception classes. CodeCompass
 has a what field in most exception classes leading to conflicting definitions in generated files.

At least one CodeCompass thrift file seems to have become invalid in thrift 0.9.3:
> [ERROR:CodeCompass/service/version-api/version.thrift:368] (last token was 'from')
Cannot use reserved language keyword: "from"

**Comment by bruntib** [comment]
Is this still an issue? In the new CodeCompass we are using the latest Thrift version (which is 0.10.0 currently) and can't see such a problem.

**Comment by bruntib** [comment]
I can't see this issue with Thrift 0.10.0 on master branch. If you can still reproduce the problem, please reopen the ticket.

**Comment by APTX** [comment]
I can confirm that CodeCompass from master builds with thrift 0.10.0.
