### ISSUE TITLE
Right menu click on non parsed files

### ISSUE THREAD

**Issue by csordasmarton** [Ericsson/CodeCompass#219]
Right clicking a non parsed file doesn't show the correct menu: 

![cc_right_menu](https://user-images.githubusercontent.com/6695818/32437077-74d89eea-c2e6-11e7-85d7-43a5ff62f9ae.png)

It throws the following error message in the web console:
```console
Uncaught TypeError: Cannot read property 'id' of undefined
    at Object._markUsages (Text.js?1509964427868:433)
    at Object._eventHandler (Text.js?1509964427868:408)
    at Text.js?1509964427868:256
    at signal (codemirror.js:1156)
    at signalDOMEvent (codemirror.js:1165)
    at CodeMirror$1.onMouseDown (codemirror.js:7224)
    at HTMLDivElement.<anonymous> (codemirror.js:3872)
_markUsages @ Text.js?1509964427868:433
_eventHandler @ Text.js?1509964427868:408
(anonymous) @ Text.js?1509964427868:256
signal @ codemirror.js:1156
signalDOMEvent @ codemirror.js:1165
onMouseDown @ codemirror.js:7224
(anonymous) @ codemirror.js:3872
```

**Comment by intjftw** [comment]
I could not reproduce this bug, the webserver gave the correct debug message. @mcserep what do you think?

**Comment by mcserep** [comment]
I managed to reproduce the issue, the cited error message is indeed present on the JavaScript console log in the browser for me, too. Right clicking in a not parsed file (e.g. in a *CMakeLists.txt*) it does not make much sense to show the C++ tools menu I guess, so the menu options should also be restricted. These menu options are shown right now - I don't know whether it is a bug or it was just simply looked over during initial design.
