### ISSUE TITLE
Keepalive script unreliable(?) in a headless environment

### ISSUE THREAD

**Issue by whisperity** [Ericsson/CodeCompass#225]
If CodeCompass Web server is started with `daemon` (the Unix standard start-stop-daemon wrapper), the `keepalive` script automatically exits after the process is started and becomes a zombie:

![image](https://user-images.githubusercontent.com/1969470/35733542-19026dbc-081e-11e8-8fb2-102dc87ffa37.png)

This results in the server crashing for any reason, be it an internal core or an external signal, the keepalive script does not anything, just gets reaped alongside the invoker `daemon` call.

**This might affect the parser too since it's the same script!**

Unfortunately, this zombie state of the shell that executes the keepalive script prevents the otherwise standard-looking `--respawn` option of `daemon`.

**Comment by whisperity** [comment]
Actually, it looks rather situational. Sometimes the keepalive script actually stays running, sometimes it zombies out.

**Comment by whisperity** [comment]
It should also not infinitely flood stuff like "cannot load shared library" as obviously such things won't get fixed by infinitely retrying. (And it can also chew away server storage space resulting in the entire thing tumbling down.)

**Comment by bruntib** [comment]
We don't have a keepalive script anymore.
