### ISSUE TITLE
Keepalive script gets into infinite loop on parsing

### ISSUE THREAD

**Issue by whisperity** [Ericsson/CodeCompass#229]
If the parser crashes due to assertion and the `--force` option is not given, the keepalive script will keep spamming 

    [ERROR] /large/whisperity/CCRP_WORKSPACE/xerces already exists. Use -f for reparsing!

If `--force` is given, it will start with dropping and then recreating all the tables, then trying the parse again, crashing, restarting, recreating the tables, starting the parse again, ...

**Comment by mcserep** [comment]
This issue was fixed during the introduction of incremental parsing.
