### ISSUE TITLE
C++ parser shouldn't add nonexistant output files to the file list

### ISSUE THREAD

**Issue by whisperity** [Ericsson/CodeCompass#233]
May be related to #230.

Consider the build action: `g++ main.cpp -o/dev/null`. This does not produce an output, but a valid build command.

Running CodeCompass with this build command logged, the following output is produced by `parser`:

```
[INFO] [cppparser] started!
[INFO] (1/1) Parsing /home/whisperity/Dummy/main.cpp
[DEBUG] File doesn't exist: /home/whisperity/Dummy/a.out
```

This file does not exist, however, it is added to the `File` table, and on the GUI, this happens:

![`a.out` is in the file list, clicking on it says `NOT PARSED`.](https://user-images.githubusercontent.com/1969470/37406094-a4696d82-2796-11e8-845c-b4dcd6531d40.png)

**Comment by bruntib** [comment]
This seems to be fixed by now.
