### ISSUE TITLE
[C++] Show the generated code for implicit members

### ISSUE THREAD

**Issue by whisperity** [Ericsson/CodeCompass#241]

**Comment by bruntib** [comment]
Didn't we have this implementation already?

**Comment by whisperity** [comment]
There was a not properly working version  many years ago (in the old closed source code) which never made it into the rework. I did a similar feature right around Flash's working to the previous release, which was never accepted, so this is (at least) the 3rd iteration indeed.

**Comment by mcserep** [comment]
Closing this issue, as the related PR #275 was closed as *stale*.
