### ISSUE TITLE
Git parser segmentation fault if folder with original VC contents missing (?)

### ISSUE THREAD

**Issue by whisperity** [Ericsson/CodeCompass#247]
If a project with Git version information is parsed, the repository is locally copied to the workdir output of CodeCompass. A `$WORKDIR/$PROJECT/workspace/version/repositories.txt` file is created with the contents:

```json
[15946978690556705777]
name=xerces-c
path=/path/to/source/dir/xerces-c
```

where `15946978690556705777` is the name of the folder in `$WORKDIR/$PROJECT/workspace/version` where the `.git` contents are available.

Now let's assume that the **original** source at `/path/to/source/dir/xerces-c` is deleted. **`It's not clear at this point if this is related to the issue!`**

When the user attempts to navigate the revision control accordion to the point where the *Branch* or *Tag* list is opened, the server segfaults away (2 times).

```
[INFO] Mongoose web server starting on port ...
[INFO] Search server started!
[INFO] Start serving search for index .../Xerces/workspace/Xerces/search
.../CodeCompass-Install/bin/keepalive: line 26:   ... Segmentation fault     (core dumped) $@
[INFO] Mongoose web server starting on port ....
[INFO] Search server started!
.../CodeCompass-Install/bin/keepalive: line 26:  ... Segmentation fault      (core dumped) $@
[INFO] Mongoose web server starting on port ...
[INFO] Search server started!
[INFO] Start serving search for index .../Xerces/workspace/Xerces/search
```

The stack trace available in a release build (the issue needs to be investigated further):

```
#0  0x00007fffed7a8acc in git_reference_free () from /usr/lib/x86_64-linux-gnu/libgit2.so.24
#1  0x00007fffedab83aa in cc::service::git::GitServiceHandler::getBranchList(
  std::vector<
    std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >,
    std::allocator<
      std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&,
  std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) ()
  from .../CodeCompass-Install/bin/../lib/serviceplugin/libgitservice.so
```

**Comment by whisperity** [comment]
Allright... so far it seems this *might* be related to server load, because I couldn't reproduce this locally.

**Comment by bruntib** [comment]
@whisperity Can we close this ticket?

**Comment by whisperity** [comment]
Something *was* weird, I can't find this issue now, we will see it resurfaces again.
