### ISSUE TITLE
Update guide for Ubuntu 18.04

### ISSUE THREAD

**Issue by whisperity** [Ericsson/CodeCompass#255]
Update the guide if using **18.04.0 LTS** is possible.

`openjdk-11-jdk` does not work. ~~The `javax.annotation` package used by Thrift violates some hierarchy. CodeCompass still installs with `openjdk-8-jdk`.~~
 - [ ] Update Thrift to `0.11` and enhance the build script to use both versions. (@zomen2) This seems to work with Java 11.

 - [X] `odb-2.4.0` does not build with `g++-7` which is default on the system. It gives a lot of `Template declaration with C linkage` errors, killing the build. (Falling back to `g++-5` works. It is available from the package manager still.)
   - [ ] ~~Updating ODB to the not yet released version `2.5` is said to work with newest GCC. See [the mailing list](https://codesynthesis.com/pipermail/odb-users/2018-June/004029.html).~~
 - [X] Google test library has been moved to the `googletest` package on which `libgtest-dev` depends. The source code is in `/usr/src/googletest`. Build procedure is the same: copy source to local folder, build, then put `libgtest*.a` to the "Dependency-Install" folder. The `/usr/src/gtest` is a symlink now. Make sure the user copies the contents of the referred folder.
 - [ ] ~~Installing the NPM packages fail, because `bufferutil` has breaking dependencies. This is installed by `ws` which is installed because `thrift` is a dependency. This needs to be investigated. See [`builderror.log`](https://github.com/Ericsson/CodeCompass/files/2020401/builderror.log).~~ **This issue exists for 16.04 LTS too.**
    - [ ] ~~(This needs to be investigated as it doesn't seem to cause problems.)*~~
    - [X] ~~Does this appear on 16.04?~~
 - [X] There is no such thing as `nodejs-legacy` in the package manager anymore. Perhaps simply installing `nodejs` works?

**Comment by whisperity** [comment]
Reopening this issue and CCing @zomen2 as he has a fix for the issues that makes OpenJDK 8 a requirement even though Ubuntu 18.04 is supplied with OpenJDK 11. Basically the Thrift version needs to be updated.

**Comment by mcserep** [comment]
Had a good time during CI configuration that why OpenJDK8 is required instead of a newer, default version available. Since Thrift 0.12 is out (instead of 0.10), it worth a try.

On the other hand ODB 2.5 is still not released, so I will just strike out that bullet point.

**Comment by bruntib** [comment]
I think this is done. If I'm mistaken, please reopen this ticket.
