### ISSUE TITLE
Don't allow services to load for projects whose corresponding parses didn't happen

### ISSUE THREAD

**Issue by whisperity** [Ericsson/CodeCompass#269]
Because of the current infrastructure dictates "1 server = 1 project", it offers the possibility of introducing a generic way to not load service plugins for a project whose corresponding parser plugins were never executed. The C++ service is useless for projects where the C++ parser never run. Same applies in general to Git and various others.

Of course, this would introduce not only potential transitive dependencies between service plugins but also the need to register which parsers were executed (together with for example an explicit "disable" of certain parsers at parse invocation), however putting this into the framework could help to alleviate the necessity of writing this logic over and over again in individual service plugins.

Partially a superissue of #232.

**Comment by mcserep** [comment]
Closing this issue, as we have moved away from the "1 server = 1 project" concept since then.
