### ISSUE TITLE
In the CLI store the workspace file names in global variables

### ISSUE THREAD

**Issue by csordasmarton** [Ericsson/CodeCompass#27]
In the CLI we use the file names (e.g. `build.json, parselog, build.log`, etc.) several places in the sourcecode. These should be `refactored to global variables or in a config file`.

**Comment by csordasmarton** [comment]
@bruntib Is this issue still relevant? We didn't have these file names in our code.

**Comment by bruntib** [comment]
No, this isn't relevant any more.
