### ISSUE TITLE
AST dump display should be lazier

### ISSUE THREAD

**Issue by bruntib** [Ericsson/CodeCompass#271]
The AST dump view in the GUI can consume too much time while loading, and also freezes the browser. The process should be lazy, and maybe not only on client side. We should consider fetching the result by ~500 lines and scrolling should trigger this event.

Although I don't know if it is useful displaying the AST of a whole translation unit. It is barely searchable and usable. I know that there will be a feature of displaying the AST of only a specific element. Until then the current solution is fine, but in long terms I wouldn't suggest to keep it.

**Comment by mcserep** [comment]
#459 closed this issue.
