### ISSUE TITLE
cpp_reparse compilation failure

### ISSUE THREAD

**Issue by mcserep** [Ericsson/CodeCompass#283]
The master branch fails to produce a **clean** build:

```
[ 49%] Building CXX object plugins/cpp_reparse/service/CMakeFiles/cppreparseservice.dir/src/asthtml.cpp.o
/home/mate/Repos/Ericsson/CodeCompass/plugins/cpp_reparse/service/src/asthtml.cpp: In member function ‘std::unique_ptr<clang::ASTConsumer> cc::service::language::ASTHTMLActionFactory::newASTConsumer()’:
/home/mate/Repos/Ericsson/CodeCompass/plugins/cpp_reparse/service/src/asthtml.cpp:223:42: error: could not convert ‘std::move<std::unique_ptr<llvm::raw_ostream>&>(((cc::service::language::ASTHTMLActionFactory*)this)->cc::service::language::ASTHTMLActionFactory::_stream)’ from ‘std::remove_reference<std::unique_ptr<llvm::raw_ostream>&>::type {aka std::unique_ptr<llvm::raw_ostream>}’ to ‘llvm::StringRef’
   return clang::CreateASTDumper(std::move(_stream), "", true, true, false);
                                          ^
plugins/cpp_reparse/service/CMakeFiles/cppreparseservice.dir/build.make:134: recipe for target 'plugins/cpp_reparse/service/CMakeFiles/cppreparseservice.dir/src/asthtml.cpp.o' failed
make[2]: *** [plugins/cpp_reparse/service/CMakeFiles/cppreparseservice.dir/src/asthtml.cpp.o] Error 1
CMakeFiles/Makefile2:677: recipe for target 'plugins/cpp_reparse/service/CMakeFiles/cppreparseservice.dir/all' failed
make[1]: *** [plugins/cpp_reparse/service/CMakeFiles/cppreparseservice.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by whisperity** [comment]
Which version of LLVM are you using?

**Comment by mcserep** [comment]
I am using the LLVM version specified in the docs, so that can be an issue. Such a breaking change should have been updated in the docs and in the future maybe direct notifications (e.g. via email) could also be sent to regular contributors.

Please update the docs with an adequate LLVM version then.

**Comment by whisperity** [comment]
The patch #248 changing the dependency was merged two months ago.

**Comment by mcserep** [comment]
@whisperity Then I overlooked it somehow that the 6.0 version was replaced by an unstable commit hash as a temporary solution. (Or maybe I did notice, I don't remember, but since working on feature branches, it did not raise any issue at that time and decided to wait for a permanent solution, only to forget it completely later.) Sorry for the inconvenience then.
Still an email reminder on dependency changes would be nice in the future if possible.

Now I downloaded and compiled LLVM 7.0.0, but have a further compilation error on CodeCompass master branch. It states that an overriden method does not exist in Clang anymore with the given signature:

```
[ 55%] Building CXX object plugins/cpp/parser/CMakeFiles/cppparser.dir/src/cppparser.cpp.o
In file included from /home/mate/Repos/Ericsson/CodeCompass/plugins/cpp/parser/src/cppparser.cpp:31:0:
/home/mate/Repos/Ericsson/CodeCompass/plugins/cpp/parser/src/ppincludecallback.h:35:16: error: ‘virtual void cc::parser::PPIncludeCallback::InclusionDirective(clang::SourceLocation, const clang::Token&, llvm::StringRef, bool, clang::CharSourceRange, const clang::FileEntry*, llvm::StringRef, llvm::StringRef, const clang::Module*)’ marked ‘override’, but does not override
   virtual void InclusionDirective(
                ^
plugins/cpp/parser/CMakeFiles/cppparser.dir/build.make:62: recipe for target 'plugins/cpp/parser/CMakeFiles/cppparser.dir/src/cppparser.cpp.o' failed
make[2]: *** [plugins/cpp/parser/CMakeFiles/cppparser.dir/src/cppparser.cpp.o] Error 1
CMakeFiles/Makefile2:964: recipe for target 'plugins/cpp/parser/CMakeFiles/cppparser.dir/all' failed
make[1]: *** [plugins/cpp/parser/CMakeFiles/cppparser.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

As I see, the same problem was already mentioned by @bruntib at the very same issue #248 you just mentioned:
> This pull request doesn't compile for me because in Clang7 the signature of `InclusionDirective()` in `PPCallbacks.h` has been changed: an extra parameter has been added. The corresponding function in our inherited class in `ppincludecallback.h` thus doesn't override this one.

I haven't checked, but maybe your fix for Clang wasn't included in the 7.0.0 version?

**Comment by bruntib** [comment]
Hi,

The fix of this issue has been merged a few hours ago: #281. This requires Clang 7 and the documentation has also been updated accordingly. Could you please try again after this fix?

And a side note: I tried to compile CodeCompass from scratch. The interesting thing is that I didn't need to compile any dependencies except for Clang (because of the RTTI issue) and Thrift. Maybe we could eliminate every other manual dependency compilation from the user guide and use the packages from Ubuntu repository, but that will be another ticket.

**Comment by whisperity** [comment]
@bruntib Upcoming changes have been prepared that does require a manual compilation of ODB, so I don't see the point of removing the discourse about ODB just to introduce it half a year (depending on when Symbol Clustering will finally land...) again.

**Comment by mcserep** [comment]
@bruntib Thanks, it compiles now.
