### ISSUE TITLE
no such file as CodeCompass/scripts/build_deps.sh in distro

### ISSUE THREAD

**Issue by Bazmundi** [Ericsson/CodeCompass#289]
Is it me or are the build instructions for CC out of date?

There appears to be no CodeCompass/scripts/build_deps.sh to build deps and no CodeCompass/scripts/build_cc.sh script.

**Comment by Bazmundi** [comment]
Ah, I find the master tag has no build tools but Earhart does.  The instructions then appear to pull down the Master tag in error.

**Comment by whisperity** [comment]
The documentation *in the Wiki* refers to the old, Earhart version. The build instructions for `master` (also known as the *Flash* version) are in the `doc/` folder checked in with the rest of the code. *Flash* (current `master`) is the ongoing development branch, and it should be as stable as possible and safe to use.

*Earhart* is an older version and evolution of CodeCompass. Development began many years ago, but eventually, the code got very convoluted and messy on every part, so a full rewrite and full refactoring was put into action. This is why *Earhart* and *Flash* are now two distinct trees, with separate roots (they can never and will never be merged together, GitHub saying it's `n` commits ahead or behind is totally bull, and should not be considered). Some features of *Earhart* had not been refactored and merged to *Flash*  yet, but all in all, **Earhart is an old and now non-developed, non-supported version**. It is more feature-rich. It can be tried out, it can be used (we still have a few running servers of it lying around here and there...), but whatever feature development was ongoing is now focused on the `master` branch.

**Comment by whisperity** [comment]
(The basic ideas and usage of CodeCompass are the same between the two versions as we, at least in spirit, kept to what our goals to achieve are with CodeCompass. You still need a compiler, build logging, a database to store the results, etc.) The biggest difference is that current CodeCompass only supports C/C++ projects, while the old code contained some tooling for parsing Java and Python code.

**Comment by Bazmundi** [comment]
#Whisperity thanks.  C/C++ is what I am after.  Now I am excited.
