### ISSUE TITLE
Starting server with empty workspace

### ISSUE THREAD

**Issue by csordasmarton** [Ericsson/CodeCompass#29]
When the server is started with an empty `workspace.cfg` file then an empty page appears in the browser.

**Comment by csordasmarton** [comment]
@bruntib Is this issue still relevant? We didn't have `workspace.cfg` file. We loads the workspaces from a working directory. By the way what happend if the working directory is empty?

**Comment by bruntib** [comment]
We have to check what happens if there aren't parsed projects in the workspace. If it is not just a blank page then this issue is not relevant.
