### ISSUE TITLE
Some fixes are needed in the parser

### ISSUE THREAD

**Issue by bruntib** [Ericsson/CodeCompass#293]
- [x] When the existence of project directory in wordir and the database is inconsistent (i.e. only one of them exists) then the error messages suggests using `-f` flag for forcing the parse. However, in this case `-f` doesn't help, it still doesn't parse anything. (Fixed by: #295)
- [x] When a new project is being parsed by `--dry-run` then the database shouldn't be created in case of a new project. With `--dry-run` no observable modification should happen in the file system.

**Comment by mcserep** [comment]
Dry-run depends on analyzing the workspace database and comparing file contents with the disk. Therefore a dry-run cannot be evaluated without an existing database. Of course it could be possible to display this information instead of creating the empty workspace database.

**Comment by mcserep** [comment]
The current operation in case of using the `--dry-run` flag with a new project is, that:
1.  the flag is removed;
2.  a warning message is printed: *"Dry-run can be only used with incremental parsing, no project found, turning --dry-run off."*

In accordance with my previous commit, I am closing this issue; but feel free to reopen it if you think that the current operation is unsatisfying.

**Comment by bruntib** [comment]
Let me reopen this issue, because I don't really agree with ignoring a flag. If I provide `--dry-run`, I don't expect any change in the database. I think it is easy to miss a log message which tells me that the parser is doing something else than I requested. I would prefer not to start parsing if some flag combinations are contradictory. I'd prefer that the user explicitly removes `--dry-run` if he or she wants to parse a new project.

**Comment by mcserep** [comment]
I understand your concerns. So, instead of a warning message, displaying an error message and aborting the process would be ok?

**Comment by bruntib** [comment]
Yes, that would be fine.

**Comment by mcserep** [comment]
@bruntib: please check #325 and merge if it is ok.
