### ISSUE TITLE
Location of an implicit node

### ISSUE THREAD

**Issue by bruntib** [Ericsson/CodeCompass#302]
The Info Tree presents all usages of a type. In case of a compiler generated copy and move constructor the parameter of these functions are also the usages of the given type. Do we present them in the Info Tree? If we do, then where do we jump when clicking on them? Their position in the database is at -1 line and column.

**Comment by whisperity** [comment]
#275 changes this behaviour to actual useful results.

**Comment by mcserep** [comment]
Closing this issue, as the related PR #272 was closed as *stale*.
