### ISSUE TITLE
"using" declarative is not handled

### ISSUE THREAD

**Issue by bruntib** [Ericsson/CodeCompass#305]
The namespace "using" declarative is not handled in the C++ parser:
```.cpp
namespace N {}
void f()
{
  using namespace N; // "N" is missing from the database
}
```

**Comment by schaumb** [comment]
Some questions have come up, and I would like to ask for your help with them:

- Multiple Instances: As [whisperity mentioned in this comment](https://github.com/Ericsson/CodeCompass/pull/487#issuecomment-1740521927), there is a one-to-many relationship with `using NS::f;`. Currently, I'm solving this by creating a separate `CppAstNode` for each to establish the connection. Is there another way, not necessarily a one-to-one binding?

- Symbol Type: Currently, the symbol type is "other," and it's not the actual symbol, as it would require some way to generate it. However, I noticed that we don't store members anywhere, and I don't see how to retrieve the AstNode based on a nodeId. Should I add members, or is it not so important?

- AstType: The AstType is currently `::usage`, which might be misleading for developers. It only has the name and not the actual function usage (call), for example. So, it can be confusing. Which AstType fits more than `::usage`?

- Namespace: Do we want to mark the namespace(s) separately? In other words, should we break down `using NS::f;` into `using [NS]::[f];`? This could make sense if we are only interested in the namespace part to see where it's defined.

- Variable templates: I tested it, and it doesn't work with variable templates yet. However, there are several errors with these variables, for example, in the following code:
```cpp
template<class T>
constexpr T var = T{};
```
I cannot get the AST on the GUI. Probably it needs to create another issue.

---

Tested with
```cpp
namespace MyNamespace
{
  void f() {}
  void g(int) {}
  void g(double){}
  class C {};

  constexpr int VAR1 = 0;

  template<class T>
  constexpr T VAR2 = T{};
}

void g() {}

using namespace MyNamespace;  // UsingDirectiveDecl
using MyNamespace::f; // UsingDecl
using MyNamespace::g;
using MyNamespace::C;
using MyNamespace::VAR1;
using MyNamespace::VAR2;

int main()
{
  f();
  g();
  g(VAR1);
  g(VAR2<double>);
}
```

**Comment by schaumb** [comment]
Answers:
---

- multiple instances -> new feature, multiple definitions (handy for templates too)
- keep "::other", probably enough to show on the frontend.
- Create a new ASTType for the "resolution"
- namespace separation as a -> new feature
- Need to investigate further.


Global variables:
---
- reparse plugin -> bug, cannot get ast nodes


Template variables:
---
- No usages -> bug
