### ISSUE TITLE
odb::object_not_persistent error

### ISSUE THREAD

**Issue by cjustin88** [Ericsson/CodeCompass#309]
Hi,

I am trying to use CodeCompass with a PostgreSQL database. I get the following error repeatedly:
```
[INFO] [cppparser] Database cleanup: /home/ubuntu/athena/build_ychiu/build/AthSimulation/Calorimeter/CaloCnv/CaloSimEventTPCnv/CMakeFiles/CaloSimEventTPCnvDictReflexDict.cxx
terminate called after throwing an instance of 'odb::object_not_persistent'
  what():  object not persistent
./keepalive: line 18: 11676 Aborted                 (core dumped) $@
[INFO] Project already exists, incremental parsing in action.
[INFO] [cppparser] preparse started!
[INFO] [cppparser] Database cleanup: /home/ubuntu/athena/build_ychiu/build/AthSimulation/Calorimeter/CaloCnv/CaloSimEventTPCnv/CMakeFiles/CaloSimEventTPCnvDictReflexDict.cxx
terminate called after throwing an instance of 'odb::object_not_persistent'
  what():  object not persistent
./keepalive: line 18: 11705 Aborted                 (core dumped) $@
[INFO] Project already exists, incremental parsing in action.
[INFO] [cppparser] preparse started!
[INFO] [cppparser] Database cleanup: /home/ubuntu/athena/build_ychiu/build/AthSimulation/Calorimeter/CaloCnv/CaloSimEventTPCnv/CMakeFiles/CaloSimEventTPCnvDictReflexDict.cxx
terminate called after throwing an instance of 'odb::object_not_persistent'
  what():  object not persistent
./keepalive: line 18: 11734 Aborted                 (core dumped) $@
```

It does not skip this file -- it retries it over and over again.

Thanks,
Justin

**Comment by mcserep** [comment]
It seems the parsing failed for some reason and then the incremental parsing fails repeatedly, probably because of an incorrect database. Try running the `CodeCompass_parser` in forced mode with flag `-f`.  
If that fails, please post the first error message here (so before any repeated try) along with your parsing command.

**Comment by cjustin88** [comment]
Thanks for the quick response!

If I set `-f`, it gets stuck on earlier files. These files have broken includes (include of a header that is missing) that is of no fault of CodeCompass. Is it possible to skip these files?

**Comment by bruntib** [comment]
Hi,

It would be better to find out why don't those translation units compile. If you check the compilation_database.json file which you give as input to the parser, then you have to see compilation commands in it which compile correctly. If your project compiles correctly without CodeCompass and it gives some error in CodeCompass, then it should be a bug on our side. What header files are these? These are the member of your project, or these are standard header files?

To answer your second question: currently there is no way of skipping compilation actions. As a workaround you can remove the unnecessary actions from the JSON file.
