### ISSUE TITLE
Multiple TUs in one build action

### ISSUE THREAD

**Issue by bruntib** [Ericsson/CodeCompass#312]
When a compilation database JSON file contains a build action which builds two translation units then only one of them will be parsed by CodeCompass: the one which is indicated in the "file" attribute of the JSON object:
```.json
[{
  "directory": "...",
  "action": "g++ a.cpp b.cpp",
  "file": "a.cpp"
}]
```

**Comment by bruntib** [comment]
This is not an error. I don't remember why I opened this ticket. In case of such a build command the logger inserts two objects to the JSON array: one for `a.cpp` and another one for `b.cpp`, so both files are parsed.
Does anybody experience any problem from this behavior? If not then we could close this ticket.

**Comment by intjftw** [comment]
It seems like no problems have emerged because of this behavior, so I close the ticket.
