### ISSUE TITLE
Problem with fully-parsed files

### ISSUE THREAD

**Issue by maqtech** [Ericsson/CodeCompass#313]
Fully parsed files don't show any information, the context menu is also not shown, instead the navigator menu is displayed.
I have parsed two projects and I have the same issue.

**Comment by bruntib** [comment]
Hi,

This sounds to be a GUI issue. What browser are you using? Could you try another one? Maybe in a different environment? Are you using a remote desktop, or do you run the browser on your machine?

**Comment by maqtech** [comment]
I'm using firefox on ubuntu 16.04 LTS. my issue is that the menu context appears on the non parsed files. and not on the parsed files.

**Comment by bruntib** [comment]
Just to be clear: you mean that the browser's default popup menu shows when you right-click on the source code, instead of the CodeCompass menu, right?
I can't reproduce this issue with the same parameters.
When you press F12 in Firefox, you can see the JavaScript console. Does an error message appear when you right-click in the source code?

**Comment by maqtech** [comment]
I got this error message:
Error: Fancytree assertion failed: Fancytree requires jQuery UI (http://jqueryui.com)

**Comment by maqtech** [comment]
this is the full log:
Loading failed for the <script> with source “http://localhost:6251/scripts/node_modules/jquery.fancytree/lib/jquery-ui.custom.js”. localhost:6251:48:1
Error: Fancytree assertion failed: Fancytree requires jQuery UI (http://jqueryui.com) jquery.min.js:2:2211
error
http://localhost:6251/scripts/node_modules/jquery/dist/jquery.min.js:2:2211
t
http://localhost:6251/scripts/node_modules/jquery.fancytree/dist/jquery.fancytree-all.min.js:33:288
<anonymous>
http://localhost:6251/scripts/node_modules/jquery.fancytree/dist/jquery.fancytree-all.min.js:33:5934
<anonymous>
http://localhost:6251/scripts/node_modules/jquery.fancytree/dist/jquery.fancytree-all.min.js:33:218
<anonymous>
http://localhost:6251/scripts/node_modules/jquery.fancytree/dist/jquery.fancytree-all.min.js:33:2
<anonymous>
http://localhost:6251/scripts/node_modules/jquery.fancytree/dist/jquery.fancytree-all.min.js:29:3
<anonymous>
http://localhost:6251/scripts/node_modules/jquery.fancytree/dist/jquery.fancytree-all.min.js:5:2
Loading failed for the <script> with source “http://localhost:6251/scripts/node_modules/jquery.fancytree/dist/src/jquery.fancytree.table.js”. localhost:6251:50:1
Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user’s experience. For more help http://xhr.spec.whatwg.org/ thrift.js:348:8

**Comment by bruntib** [comment]
Hi,

I installed Ubuntu 16.04 under VirtualBox, and set up CodeCompass. I could reproduce the error with Firefox. However, when I port-forwarded CodeCompass to the host machine and opened Firefox on the host, the right-click worked.

Moreover I can't reproduce the bug when I run CodeCompass on the host machine with Firefox.

So until we investigate the bug in VirtualBox, I suggest to try another browser.

**Comment by bruntib** [comment]
Hi,

I've found a solution for the problem. After accepting #314 the issue should be solved.
