### ISSUE TITLE
libcppreparseservice.so can't find clang::ASTConsumer

### ISSUE THREAD

**Issue by TheLorax** [Ericsson/CodeCompass#317]
I'm trying to build code compass in a Docker container. The build finished, but I'm getting the following runtime error.
```
root@2a058e9d3587:/# /usr/local/bin/CodeCompass_webserver 
terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to load "/usr/local/lib/serviceplugin/libcppreparseservice.so": /usr/local/lib/serviceplugin/libcppreparseservice.so: undefined symbol: _ZTIN5clang11ASTConsumerE
Aborted
```
Running ldd on both CodeCompass_webserver and libcppreparseservice.so doesn't list any libclang dependencies. I double checked with strace, and sure enough, the loader doesn't even try to locate libclang, so it's not just some kind of LD_LIBRARY_PATH problem. Did I just build it wrong? I'm including my Dockerfile here.
[Dockerfile.txt](https://github.com/Ericsson/CodeCompass/files/2964579/Dockerfile.txt)

Thanks!

**Comment by TheLorax** [comment]
I should also mention, I'm very open to donating that Dockerfile to the project if it eventually starts working. I feel like most people would want to use this project as a drop-in service.

**Comment by bruntib** [comment]
Hi,

This error message occurs when LLVM/Clang is not compiled with RTTI. You're compiling LLVM and Clang separately and RTTI is missing from the Clang part. Note, however, that LLVM/Clang compilation should happen in one step: the `cfe-<version>` directory should be copied under LLVM as `<path_to_llvm>/tools/clang`. After this you'll have to compile LLVM and Clang in one step with `cmake` and `make`. For details see the "Known issues" part of this documentation: https://github.com/Ericsson/CodeCompass/blob/master/doc/deps.md#known-issues

**Comment by TheLorax** [comment]
That fixed it. Thanks. Once I'm done cleaning up the Dockerfile I'll offer a pull request if there is interest. Let me know.
