### ISSUE TITLE
CppParserTest fails over sqlite database

### ISSUE THREAD

**Issue by mcserep** [Ericsson/CodeCompass#326]
2 of 10 test cases fail in `CppParserTest` on the master branch:
1. `CppParserTest.FunctionCall`
2. `CppParserTest.Variable`

All tests are passed with a PostgreSQL database, this issue only occurs with an SQLite database.

Test log:
> 2: [  INFO ] /home/mate/Repos/Ericsson/CodeCompass/plugins/cpp/test/src/cpptest.cpp:24:: Using database for tests: sqlite:database=/home/mate/cc/test_db.sqlite
> 2: [==========] Running 10 tests from 1 test case.
> 2: [----------] Global test environment set-up.
> 2: [----------] 10 tests from CppParserTest
> 2: [ RUN      ] CppParserTest.FilesAreInDatabase
> 2: [       OK ] CppParserTest.FilesAreInDatabase (3 ms)
> 2: [ RUN      ] CppParserTest.SimpleFunction
> 2: [       OK ] CppParserTest.SimpleFunction (1 ms)
> 2: [ RUN      ] CppParserTest.FunctionDeclarationOnly
> 2: [       OK ] CppParserTest.FunctionDeclarationOnly (0 ms)
> 2: [ RUN      ] CppParserTest.FunctionWithMultipleDeclarations
> 2: [       OK ] CppParserTest.FunctionWithMultipleDeclarations (0 ms)
> 2: [ RUN      ] CppParserTest.FunctionCall
> 2: /home/mate/Repos/Ericsson/CodeCompass/plugins/cpp/test/src/cppparsertest.cpp:238: Failure
> 2: Value of: false
> 2:   Actual: false
> 2: Expected: true
> 2: /home/mate/Repos/Ericsson/CodeCompass/plugins/cpp/test/src/cppparsertest.cpp:238: Failure
> 2: Value of: false
> 2:   Actual: false
> 2: Expected: true
> 2: /home/mate/Repos/Ericsson/CodeCompass/plugins/cpp/test/src/cppparsertest.cpp:238: Failure
> 2: Value of: false
> 2:   Actual: false
> 2: Expected: true
> 2: [  FAILED  ] CppParserTest.FunctionCall (1 ms)
> 2: [ RUN      ] CppParserTest.Typedef
> 2: [       OK ] CppParserTest.Typedef (0 ms)
> 2: [ RUN      ] CppParserTest.Record
> 2: [       OK ] CppParserTest.Record (1 ms)
> 2: [ RUN      ] CppParserTest.Enum
> 2: [       OK ] CppParserTest.Enum (1 ms)
> 2: [ RUN      ] CppParserTest.Variable
> 2: /home/mate/Repos/Ericsson/CodeCompass/plugins/cpp/test/src/cppparsertest.cpp:548: Failure
> 2:       Expected: n.symbolType
> 2:       Which is: 4-byte object <00-00 00-00>
> 2: To be equal to: model::CppAstNode::SymbolType::FunctionPtr
> 2:       Which is: 4-byte object <02-00 00-00>
> 2: /home/mate/Repos/Ericsson/CodeCompass/plugins/cpp/test/src/cppparsertest.cpp:563: Failure
> 2: Value of: false
> 2:   Actual: false
> 2: Expected: true
> 2: /home/mate/Repos/Ericsson/CodeCompass/plugins/cpp/test/src/cppparsertest.cpp:563: Failure
> 2: Value of: false
> 2:   Actual: false
> 2: Expected: true
> 2: /home/mate/Repos/Ericsson/CodeCompass/plugins/cpp/test/src/cppparsertest.cpp:563: Failure
> 2: Value of: false
> 2:   Actual: false
> 2: Expected: true
> 2: /home/mate/Repos/Ericsson/CodeCompass/plugins/cpp/test/src/cppparsertest.cpp:563: Failure
> 2: Value of: false
> 2:   Actual: false
> 2: Expected: true
> 2: /home/mate/Repos/Ericsson/CodeCompass/plugins/cpp/test/src/cppparsertest.cpp:563: Failure
> 2: Value of: false
> 2:   Actual: false
> 2: Expected: true
> 2: /home/mate/Repos/Ericsson/CodeCompass/plugins/cpp/test/src/cppparsertest.cpp:563: Failure
> 2: Value of: false
> 2:   Actual: false
> 2: Expected: true
> 2: /home/mate/Repos/Ericsson/CodeCompass/plugins/cpp/test/src/cppparsertest.cpp:563: Failure
> 2: Value of: false
> 2:   Actual: false
> 2: Expected: true
> 2: /home/mate/Repos/Ericsson/CodeCompass/plugins/cpp/test/src/cppparsertest.cpp:563: Failure
> 2: Value of: false
> 2:   Actual: false
> 2: Expected: true
> 2: /home/mate/Repos/Ericsson/CodeCompass/plugins/cpp/test/src/cppparsertest.cpp:563: Failure
> 2: Value of: false
> 2:   Actual: false
> 2: Expected: true
> 2: /home/mate/Repos/Ericsson/CodeCompass/plugins/cpp/test/src/cppparsertest.cpp:563: Failure
> 2: Value of: false
> 2:   Actual: false
> 2: Expected: true
> 2: /home/mate/Repos/Ericsson/CodeCompass/plugins/cpp/test/src/cppparsertest.cpp:563: Failure
> 2: Value of: false
> 2:   Actual: false
> 2: Expected: true
> 2: /home/mate/Repos/Ericsson/CodeCompass/plugins/cpp/test/src/cppparsertest.cpp:563: Failure
> 2: Value of: false
> 2:   Actual: false
> 2: Expected: true
> 2: [  FAILED  ] CppParserTest.Variable (1 ms)
> 2: [ RUN      ] CppParserTest.Namespace
> 2: [       OK ] CppParserTest.Namespace (0 ms)
> 2: [----------] 10 tests from CppParserTest (8 ms total)
> 2: 
> 2: [----------] Global test environment tear-down
> 2: [==========] 10 tests from 1 test case ran. (8 ms total)
> 2: [  PASSED  ] 8 tests.
> 2: [  FAILED  ] 2 tests, listed below:
> 2: [  FAILED  ] CppParserTest.FunctionCall
> 2: [  FAILED  ] CppParserTest.Variable
> 2: 
> 2:  2 FAILED TESTS
> 2/2 Test `#2`: cppparser ........................***Failed    3.48 sec

**Comment by mcserep** [comment]
Can you have a look at this @bruntib , when you have time?

**Comment by bruntib** [comment]
Sure, I'll schedule a review session this week so I check your fixes. Sorry for my slowness.
