### ISSUE TITLE
Move Thrift generated files into the build directory

### ISSUE THREAD

**Issue by mcserep** [Ericsson/CodeCompass#339]
Upon CodeCompass compilation, Thrift currently generates files into the source folder (`gen-cpp`, `gen-java`, `gen-js` directories), instead of the build location. Since these are generated files, they should be created in the build folder, which would also result in an easier cleanup.

**Comment by whisperity** [comment]
I think I have created a patch that refactored and fixed the scope and location of ***every** (not just Thrift) generated thing. See #270. Maybe it just never got merged since its inception.
