### ISSUE TITLE
code viewer does not jump back to the same line

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/CodeCompass#382]
when scrolling the code, pressing goto definition and then the user would like to jump back to the same line where it was . The code viewer does not jump back to the correct line, but to the beginning of the file.

**Comment by mcserep** [comment]
Just for clarification: how does the user jumps backs to the previous file? With the back button of the browser?

**Comment by dkrupp** [comment]
yes. back button. the code line is not followed in the url whiel scrolling.

**Comment by mcserep** [comment]
As I can see, when clicking at a location in the code, the permalink is simply not modified. So the `select` parameter in the query string is not updated. I think it never was, but it would be nice, if it would work in the way you described.
