### ISSUE TITLE
[CI] Cache build of dependencies if the release is up-to-date

### ISSUE THREAD

**Issue by whisperity** [Ericsson/CodeCompass#394]
Given #385, ODB will now be compiled by the user locally. This poses a problem on Travis as 

 - downloading build2
 - building build2
 - downloading odb
 - building odb

takes a lot of time (compared to Thrift and GTest which are trivial time, a minute or so at most).

Travis has a [caching feature](https://docs.travis-ci.com/user/caching/) which should be investigated. Given that we are pegged to a Build2 version in the guide, we could:
 - once download Build2
 - install it in the Travis environment
 - download ODB
 - compile ODB
 - install it in the environment

What could be cached is the installed ODB libraries (and its dependency libs). Build2 can be scrapped afterwards by the VM shutdown. In case a newer ODB release happens during our time (and hence the automated install would download a different code...!), the cache has to be set up to redownload Build2 and ODB and do the whole thing over again.

----

Actually, this could be done for Thrift, too!

**Comment by whisperity** [comment]
Oh, wait, I see this is already done on the patch of #385. Could be that my recent other PR (#393) is just not using the cache because I touched `.travis.yml`. Okay...

**Comment by mcserep** [comment]
In Travis there is one cache per branch and PR's has their own cache. I don't know whether that can be overridden at all. Maybe that's why the cache wasn't used in your other PR.
