### ISSUE TITLE
Make diagram SVG downloadable

### ISSUE THREAD

**Issue by intjftw** [Ericsson/CodeCompass#399]
Currently the only option when displaying a diagram is to create a screenshot of it, which is likely blurry, depending on the size. There is the "Export SVG" option, but the exports cannot be directly saved as PNG, It would be useful to have a donwload option.

**Comment by zporky** [comment]
Why not good enough to export SVG and then off-line convert it to PNG?

**Comment by intjftw** [comment]
@zporky That is also a possible solution, would spare some code. The "make it downloadable" is the important part.

**Comment by intjftw** [comment]
Right now, the exported SVG is embedded in the HTML source of the page. It cannot be downloaded as an image. Even if it was downloadable, only the .html file could be saved. However, converting to PNG might not be a necessity if this feature is ever realized.

**Comment by zporky** [comment]
Ok, I have got it! You are right, this download feature should be implemented.
