### ISSUE TITLE
Fetch the latest Build2 version

### ISSUE THREAD

**Issue by mcserep** [Ericsson/CodeCompass#413]
As described in #411 , for some yet unknown reasons, Build2 version 0.12.0 no longer succeeds to build on Ubuntu 18.04 after version 0.13.0 was released.

It shall be investigated whether this was intended by developers of Build2. If so, a general solution would be to always download the latest version of Build2.

**Comment by bruntib** [comment]
Fixed by #411.

**Comment by mcserep** [comment]
This is not fixed by #411, as updating to version 0.13.0 currently fixed the problem, but unless we dynamically fetch the newest version, this might become a problem in the future again.
