### ISSUE TITLE
AST dump for files are too big

### ISSUE THREAD

**Issue by bruntib** [Ericsson/CodeCompass#422]
Right click on a C/C++ source file -> C++ -> Show AST HTML.
This menu item fetches the AST of the whole translation unit. This is almost always so big that it either doesn't arrive from the server or can't be rendered by the browser. In the latter case the browser may consume all memory (including swap) of the client machine, so it freezes the whole OS.
AST query for files should be either eliminated from the GUI, or we should make it lazy: all tree nodes are closed by default.

**Comment by mcserep** [comment]
Also, the AST is not properly formatted in the browser, there are unexpected line breaks in some cases.
The simple solution would be embedding it into a `<pre>` element.
