### ISSUE TITLE
Database name must not contain hyphen ('-') character

### ISSUE THREAD

**Issue by zporky** [Ericsson/CodeCompass#426]
Postgres database command CREATE DATABASE does not accept hyphen character in the database name. Since users tend to specify database names for CodeCompass_parser like "pgsql: ... database=cc-master-0726", this cause a postgres error and a subsequent abortion of the parser. 

We have to search for hyphens in the CodeCompass parser database argument and either have to (1) escape, (2) replace (e.g. to underscore char) or just (3) warn the user and abort the parsing.

Also, put this information to the user guide.

**Comment by bruntib** [comment]
PostgreSQL has a strange behavior on identifiers: these are case-sensitive, but by default characters are converted to lowercase. So not just '-' requires special treatment but uppercase characters too. In PostgreSQL clients the solution is surrounding these names with quotation marks. The solution should be finding how to take these surrounding quotation marks through ODB.

**Comment by mcserep** [comment]
Fixed with #426, the database name had to be put between quotation marks.
