### ISSUE TITLE
How to identify an AST node across translation units?

### ISSUE THREAD

**Issue by bruntib** [Ericsson/CodeCompass#427]
Currently our hand-made mangled name and later USR will be able identifying AST nodes across translation units uniquely. However, what happens in those cases when a project contains two executables?
```.cpp
// Executable 1: first.cpp
class MyClass {
public:
  int i;
  virtual void f() = 0;
};
int main()
{
}

// Executable 2: second.cpp
class MyClass {
public:
  int i;
};
int main()
{
}

// Build
// g++ first.cpp
// g++ second.cpp
```
When opening InfoTree for classes, CodeCompass is able to show whether the given class is an abstract type. We can do that, since we store this boolean information in table `CppType`. Due to historical and some unsolved technical reasons column `mangledNameHash` in `CppEntity` (from which `CppType` inherits) is not unique. It should be unique, since the idea behind these tables is that it contains general information about a named entity. But even if `mangledNameHash` is not unique in this table, how could we distinguish which binary's symbol has been clicked in the GUI for InfoTree? Mangled name doesn't contain this piece of information.

**Comment by bruntib** [comment]
I don't know if this observation is related, but let's consider the following example:
```.cpp
void func(int param);
void func(int param);
void func(int param)
{
}
```
When opening the InfoTree of a `func` declaration and clicking on its parameters in the InfoTree, it jumps to the parameters of the corresponding `func` declaration. This is a good behavior. We can do this, because currently in this code fragment the mangled names of the three `param` variables are different. This also means that we can't say that these three variables are semantically equivalent. Fortunately we don't have a feature in CodeCompass which requires the ability of connecting these variables.

When changing to USR, we should check if it generates different identifiers for these three variables. If they have the same USR then we can't eliminate `astNodeId` column from `CppEntity`, because this column binds the entity to a specific declaration. Finding this connection will also cost some extra operations.

**Comment by whisperity** [comment]
First things first, neither the mangled name nor the USR will "really" contain this information, as while some aspects of ODR is applicable to a program level and not the translation unit level, "multiple programs" are not defined by the standard at all. However, #198 does exactly this, as long as we are using a `compile_commands.json` that also contains link commands. At encountering of an ambiguous symbol set, it uses the link graph (flattened at parse time so it's not heavy on the service time) to highlight symbols that are from TUs that are known to be linked together.
