### ISSUE TITLE
[C++] Compiler diagnostics are silent in parser output

### ISSUE THREAD

**Issue by whisperity** [Ericsson/CodeCompass#437]
As discovered in #432 with #403 being the potential culprit, the Clang compiler diagnostics during parse time are not printed to the parser's standard streams anymore:

When analysing CodeCompass with CodeCompass itself:

~~~~
[INFO] (62/129) Parsing /home/w/Work/CodeCompass/Source/webserver/src/session.cpp
[INFO] (63/129) Parsing /home/w/Work/CodeCompass/Source/webserver/src/sessionmanager.cpp
2 warnings generated.
[INFO] (64/129) Parsing /home/w/Work/CodeCompass/Source/webserver/src/threadedmongoose.cpp
[INFO] (65/129) Parsing /home/w/Work/CodeCompass/Source/webserver/src/mongoose.c
[INFO] (66/129) Parsing /home/w/Work/CodeCompass/Source/webserver/authenticators/plain/src/plugin.cpp
2 warnings generated.

[...]

2 errors generated.
Error while processing /home/w/Work/CodeCompass/Source/plugins/cpp/test/src/cppparsertest.cpp.
[WARNING] (100/129) Parsing /home/w/Work/CodeCompass/Source/plugins/cpp/test/src/cppparsertest.cpp has been failed.
~~~~

Previously, the Clang diagnostics were formatted and output as if a true compiler was running. While it's less of a problem for warnings, for errors it's challenging to understand the output (especially without booting a server) - it says **2 errors generated** but never says what the errors are.

**Comment by mcserep** [comment]
#403 have added `DiagnosticConsumer` to `ClangTool`:

```cpp
clang::tooling::ClangTool tool(*compilationDb, command_.Filename);

DiagnosticMessageHandler diagMsgHandler(_ctx.srcMgr, _ctx.db);
tool.setDiagnosticConsumer(&diagMsgHandler);
```

In `ClangTool` the `DiagConsumer` is `nullptr` by default and the default operation in that case is to use `TextDiagnosticPrinter`.  This is overridden now.

```cpp
TextDiagnosticPrinter DiagnosticPrinter(llvm::errs(), &*DiagOpts);
DiagnosticsEngine Diagnostics(IntrusiveRefCntPtr<DiagnosticIDs>(new DiagnosticIDs()), &*DiagOpts,
       DiagConsumer ? DiagConsumer : &DiagnosticPrinter, false);
```

So our own `DiagnosticMessageHandler` shall include printing out these messages if we want this feature.

**Comment by mcserep** [comment]
Maybe inherit `DiagnosticMessageHandler` from `TextDiagnosticPrinter` instead of the abstract base class `DiagnosticConsumer`?
