### ISSUE TITLE
Reparse is slow for files

### ISSUE THREAD

**Issue by intjftw** [Ericsson/CodeCompass#443]
Showing C++ AST is very slow for large files (or files that include large files). The AST generation should timeout after a short period of time or the included files should not be included in the AST (if that is possible). Any other solution that guarantees that the user won't have to wait a very long time could work.

**Comment by bruntib** [comment]
I think this ticket is a duplicate of #422.

**Comment by intjftw** [comment]
Oh, okay, thanks!
