### ISSUE TITLE
Display C++ compiler diagnostic messages on frontend

### ISSUE THREAD

**Issue by mcserep** [Ericsson/CodeCompass#452]
Since #403, C++ compiler diagnostic messages are added to the database (`BuildLog` table). However these error messages and warnings are not shown on the web GUI at all.  They could be popped up e.g. when clicking on the *Partially parsed* or *Not parsed* label. (They are actually clickable, the cursor changes, but nothing is done.)
![image](https://user-images.githubusercontent.com/7405458/90795918-f18fc580-e30e-11ea-9c57-7e02267cd5e2.png)

Demo: http://codecompass.net/demo/#wsid=CodeCompass&fid=17693769208924111025&select=1|1|1|1&center=text

**Comment by intjftw** [comment]
Resolved in #512.
