### ISSUE TITLE
Update or drop Wiki page

### ISSUE THREAD

**Issue by bruntib** [Ericsson/CodeCompass#453]
Our Wiki still describes Earhart release: https://github.com/Ericsson/CodeCompass/wiki
Unfortunately Wiki is no too suitable for having documentation of multiple releases. And we're maintaining our documentation in .md files which are version controlled and available from the main GitHub page.

My suggestion is replacing the important pages of our Wiki to .md files under Earhart branch and remove the current Wiki. I think we shouldn't duplicate our documentations. What do you think?

**Comment by mcserep** [comment]
I completely agree, I have already thought about the same.
