### ISSUE TITLE
Rename CppType to CppRecord in database

### ISSUE THREAD

**Issue by bruntib** [Ericsson/CodeCompass#454]
Table name `CppType` is deceiving: it stores only record types (class, struct, union) and not all types. For example enums go to a different table.

When generating info tree for the return type of a function we're only searching entries in `CppType`: https://github.com/Ericsson/CodeCompass/blob/6dfc28a890af17947b4e11f58479e637e56eb5ec/plugins/cpp/service/src/cppservice.cpp#L455-L456
Return type of functions returning an enum type is thus not shown in info tree (see #11).

**Comment by zporky** [comment]
Sorry, just to clarify: "When generating info tree for the return type of a function we're only searching entries in CppType". Is this means that the return type of functions returning build in types are also not shown? I made some tests and this seems to be the case...

**Comment by bruntib** [comment]
Exactly. Maybe we should create another ticket for handling builtin types, because currently those are not stored at all in our database.

**Comment by zporky** [comment]
Well, this needs to be considered what info_tree of a built in type means.
On one side: what information do you want to know about "int"? On the other
hand, usage places of these types could be interesting.

bruntib <notifications@github.com> ezt írta (időpont: 2020. aug. 31., H,
15:35):
