### ISSUE TITLE
Show info tree on left click event

### ISSUE THREAD

**Issue by bruntib** [Ericsson/CodeCompass#455]
From user experience point of view it is important that frequent functionalities are available through as less operations as possible. Info tree is the most frequently used feature, so it should be visible immediately on left click event.

This implies that file tree is automatically hidden. Maybe this is not a too big problem. If file tree is required to be always seen then we may consider splitting accordion panel on the left and displaying file tree permanently besides other tabs.

**Comment by zporky** [comment]
Not only using namespace, but simple using declarations should be considered
