### ISSUE TITLE
Parser quits with segfault if ran with --help flag

### ISSUE THREAD

**Issue by filbeofITK** [Ericsson/CodeCompass#491]
If one runs the ``CodeCompass_parser --help `` command it displays the information needed, but then quits with: ``Segmentation fault (core dumped)``.

**Comment by zporky** [comment]
Is not this the same as issue #405?
There is a pull request supposed to solve the issue: https://github.com/Ericsson/CodeCompass/pull/490 most likely caused boost.program_options.

**Comment by mcserep** [comment]
Yes, this is the same.
