### ISSUE TITLE
New CC version?

### ISSUE THREAD

**Issue by intjftw** [Ericsson/CodeCompass#550]
With the introduction of Python and Java support into CodeCompass, I think it's time to move on from Flash to the next major version.

@zporky @mcserep @bruntib  what do you think?

**Comment by zporky** [comment]
Perhaps also integrating Java 1.0?

gsd

Anett Fekete ***@***.***> ezt írta (időpont: 2021. nov. 29.,
H, 10:30):

**Comment by mcserep** [comment]
I agree with @intjftw. With the *Flash* version of CodeCompass, the *rolling-release* methodology was planned to be implemented - also called *continuous delivery*. This would mean new features are frequently released in new versions and while semantic versioning is not required by definition, it is almost unavoidable with *continuous delivery*. The process could also be significantly automatized with proper tools, e.g. by using [conventional commits](https://www.conventionalcommits.org/).

In my opinion (as specialized in software technology), this *rolling-release* methodology was implemented incompletely in CodeCompass, as there are no releases at all, new features and bug fixes are just merged into *master*. And while one could argue that every commit on the master branch is a new release, without version information, this is more like "rolling-without-release" :)

I agree that at this point of the project it would be more beneficial to step back to the *point release development model*. The *Flash* version could be branched of *master* and only receive required bug fixes from now on. New features should be continued to be merged into master.
In the long run, a new stable release could be made I think every year, providing support only for the latest stable release, so our resources on not wasted too much on maintenance.

I propose not to integrate Java in *Flash*, as it is not thoroughly tested yet (like other parts of the project), and is not considered stable.

**Comment by intjftw** [comment]
I agree we should just "close" _Flash_, and move on to the next major version. I also agree that we should go back to _point release development_, since mostly major modifications are made to CC nowadays (e.g. Java, Python, C#, project hosting, UnitAttributes plugin, along with reworking the entire frontend).

**Comment by mcserep** [comment]
**Credits of the Earhart release:**

| Name | Components
| ------ | ------ |
| Áron Baráth | Java parser |
| Zoltán Borók-Nagy | C++ parser, Web server |
| Tibor Brunner | C++ parser, GUI development, diagrams |
| Máté Cserép | CodeBites, diagrams |
| Tamás Cséri | Doxygen comment parser, GIT |
| Attila Góbi | Build environment |
| Gábor Alex Ispánovics | C++ parser, Search |
| Dániel Krupp | Architect |
| Zoltán Porkoláb | Idea, C++ Expert |
| Zalán Szűgyi | C++ parser, parser infrastructure |

**Proposed Credits of the Flash release:**

| Name | Components
| ------ | ------ |
| Zoltán Borók-Nagy     | C++ plugin |
| Tibor Brunner              | C++ plugin, Metrics plugin, web GUI, diagrams |
| Máté Cserép                | C++ plugin, CodeBites, diagrams |
| Tamás Cséri                  | Git plugin |
| Márton Csordás           | Build infrastructure, web GUI |
| Anett Fekete                | C++ plugin |
| Gábor Alex Ispánovics | C++ plugin, search plugin |
| Zoltán Porkoláb           | Project owner, C++ expert |
| Richárd Szalay             | C++ plugin |

I could obviously leave out the contribution of someone, sorry for that in advance 😄  E.g. I was especially unsure about the contributions of Márton Csordás.  
Please comment your proposed updates here.

**Comment by zporky** [comment]
Bence Nagy: Python plugin
Gergő Horváth: Java plugin

**Comment by mcserep** [comment]
I omitted them, because those components are not planned to be part of the Flash release.

**Comment by intjftw** [comment]
Is the above table final? I'd like to commit it to master, but I can't quite remember if we talked about any changes at the last meeting.

**Comment by mcserep** [comment]
No, it was not. I have updated it.
