### ISSUE TITLE
New web frontend

### ISSUE THREAD

**Issue by mcserep** [Ericsson/CodeCompass#590]
The design concept of the current web frontend is considered outdated in some terms. The task is to completly redesign and implement a new web frontend for CodeCompass from scratch. Technologies and libraries to use:
 - React
 - Material Design

The new frontend shall use the existing RPC-based Thrift backend and its provided features of CodeCompass.

**Comment by mdeme01** [comment]
The new frontend is currently in development [here](https://github.com/mdeme01/CodeCompass/tree/new-frontend/webgui-new).

So far, the following features were implemented:
- Switching between workspaces
- Viewing files in the file manager and file contents in the editor
- Searching and displaying search results
- Generating metrics and diagrams for files/directories

Let me know if there are any problems, or if the design should be different.

**Comment by mcserep** [comment]
@mdeme01 If you think that your development is ready for a first round of review, please open a pull request. It is easier to review the code that way and leave remarks.

You can still push new commits to your branch of course and the PR will auto-update.

**Comment by mdeme01** [comment]
Pull request is ready [here](https://github.com/Ericsson/CodeCompass/pull/595).

**Comment by mcserep** [comment]
With @intjftw, we have deployed the current version of the new frontend for review:  
https://codecompass.net/demo/new/

**Comment by intjftw** [comment]
Closed by #595.
