### ISSUE TITLE
Extend documentation on how to build and develop New Frontend

### ISSUE THREAD

**Issue by mcserep** [Ericsson/CodeCompass#605]
Your thesis @mdeme01 contains valuable information on how to build and develop the *New Frontend*. This should be included in the project documentation as well. Please extend it accordingly.

**Comment by intjftw** [comment]
There is a documentation in `webgui-new/README.md`. However, this documentation is insufficient, and contains some errors regarding the access path of the new frontend. @mdeme01 please put the documentation in the `doc` directory to the official build guide, and include all build commands. Also, including the user documentation from your thesis would be useful.
