### ISSUE TITLE
Parse status button to show build info

### ISSUE THREAD

**Issue by intjftw** [Ericsson/CodeCompass#608]
In the old version of the UI, the parse status button on top of an open file could be clicked. On right click, a pop-up window appeared with a table of the warnings and errors given by the compiler during parsing.

**Comment by mdeme01** [comment]
Could you show me an example where I can see how these build logs are shown? So far, all the files I clicked had the 'No build logs for this file' message.

**Comment by intjftw** [comment]
[This file](https://codecompass.net/demo/#wsid=CodeCompass&fid=11852034569623368286&select=1|1|1|1&center=text) has a couple of them (`plugins/cpp/service/src/cppservice.cpp` in CodeCompass).
