### ISSUE TITLE
Google Analytics events in new frontend

### ISSUE THREAD

**Issue by intjftw** [Ericsson/CodeCompass#616]
The previous version of the UI had Google Analytics integrated in the form of events. These are intended to capture important activity from users anonymously. We use the data for statistical purposes. The new frontend should also integrate the events. They should be featured in every possible function, such as AST node clicks, displaying git blame views, diagrams, documentation, moving between files, etc.

**Comment by intjftw** [comment]
A typical implementation of an event in CodeBites can be seen [here](https://github.com/Ericsson/CodeCompass/blob/000cfc29d4517d06333c4da7e9aa76cb0eb74ed6/webgui/scripts/codecompass/view/codeBites.js#L133). @mdeme01 please write here if you need more help with this.

**Comment by mdeme01** [comment]
I've found this [npm package](https://www.npmjs.com/package/react-ga4), which easily integrates Google Analytics into React. However, it needs a measurement ID for initialization. I see that the previous UI uses it in [ga.js](https://github.com/Ericsson/CodeCompass/blob/master/webgui/scripts/ga.js#L6), but it is unclear to me where it comes from.

**Comment by mcserep** [comment]
@mdeme01 The mentioned React-GA package should work fine, we also use that in TMS without any issues.

About the measurement ID, as described in the Usage Guide:

> To enable this feature, a `ga.txt` file should be created under the workspace directory (`--workspace` or `-w` flag given to the server). The `ga.txt` file shall consist of a single line, containing the Google Analytics *Tracking ID* (format `UA-XXXXXX-X`) or *Measurement ID* (format `G-XXXXXXX`). When configured correctly, upon starting a `CodeCompass_webserver`, the *"Google Analytics monitoring enabled."* informational status message will be displayed.
> 
> **Note:** without explicitly creating the `ga.txt` file in the workspace directory, the Google Analytics integration is disabled and no related code is executed in the browser. **This is the default behaviour.**

See e.g. https://codecompass.net/demo/ga.txt . You should also be prepared if the `ga.txt` is not served (404), in that case GA should be disabled.

**Comment by mdeme01** [comment]
I see, thanks. However, I will wait until #615 gets merged, to avoid conflicts.

**Comment by mcserep** [comment]
> I see, thanks. However, I will wait until #615 gets merged, to avoid conflicts, as I think this could be fixed in a separate PR instead.

All issues should be fixed in a separate PR.

Due to summer holidays, we can only start reviewing #615 soon, so in case you made further contributions to the other remaining issues, please open a PR for them. In case you think an issue is highly dependenant on a fix for another one, you may start a new branch from that feature-branch.
