### ISSUE TITLE
libindexerservice.so installation directory

### ISSUE THREAD

**Issue by bruntib** [Ericsson/CodeCompass#71]
`libindexerservice.so` is installed directly under `lib` directory. This file is used for parsing for sure. If it is not used for service then this file should go under `parserplugin` directory.

**Comment by csordasmarton** [comment]
We use `parserplugin` directory only for parsers which inherit from `AbstracParser` and have a `make` and a `getOptions` function. We can't put the `indexservice` in this directory for this reason.
