### ISSUE TITLE
Incorrect ODB installation to webserver Docker images

### ISSUE THREAD

**Issue by mcserep** [Ericsson/CodeCompass#742]
Running `CodeCompass_webserver` in the `web-pgsql` image yields the following error:  
> CodeCompass_webserver: error while loading shared libraries: libodb-2.5.0-b.25.so: cannot open shared object file: No such file or directory

The `runtime-pgsql` image is not affected by the bug and works as expected.

**Comment by Seeker04** [comment]
In the `dev` container:
```bash
ldd $(which CodeCompass_webserver) | grep libodb
	libodb-2.5.0-b.25.so => /usr/local/lib/libodb-2.5.0-b.25.so (0x00007fdd153f6000)
	libodb-sqlite-2.5.0-b.25.so => /usr/local/lib/libodb-sqlite-2.5.0-b.25.so (0x00007fdd153be000)
```

In the `web-pgsql` container:
```bash
ldd $(which CodeCompass_webserver) | grep libodb
	libodb-2.5.0-b.25.so => not found
	libodb-pgsql-2.5.0-b.25.so => not found
```
because the shared object simply does not exist in the latter image:
```bash
ls /usr/local/lib/libodb-2.5.0-b.25.so /usr/local/lib/libodb-sqlite-2.5.0-b.25.so
ls: cannot access '/usr/local/lib/libodb-2.5.0-b.25.so': No such file or directory
ls: cannot access '/usr/local/lib/libodb-sqlite-2.5.0-b.25.so': No such file or directory
```
These are the only two missing according to `ldd $(which CodeCompass_webserver) | grep "not found"`.

**Comment by mcserep** [comment]
> These are the only two missing according to ldd $(which CodeCompass_webserver) | grep "not found".

@Seeker04 Thanks for investigating this, most likely this issue it that simple.
The task is to locate where the *libodb* was removed from the *web* image, and readd it. Key suspect is #644.
